### ISSUE TITLE
*QRLJACKING ISSUE IN KALI LINUX*

### ISSUE THREAD

**Issue by insistence-essenn** [OWASP/QRLJacking#107]
QrlJacker Module(grabber/whatsapp) >   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sourjayon/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sourjayon/QRLJacking/QRLJacker/core/browser.py", line 116, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sourjayon/QRLJacking/QRLJacker/core/browser.py", line 132, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

I get this error

**Comment by jamesmiller9048** [comment]
i can't even launch QRLJacking.py file i get the following error

Traceback (most recent call last):
  File "./QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/home/kali/Desktop/QRLJacking-master/QRLJacker/core/Cli.py", line 5, in <module>
    from core import utils,db,module,Settings,browser
  File "/home/kali/Desktop/QRLJacking-master/QRLJacker/core/module.py", line 4, in <module>
    from core import utils,Settings,Cli,db,browser
  File "/home/kali/Desktop/QRLJacking-master/QRLJacker/core/browser.py", line 4, in <module>
    from user_agent import generate_user_agent
ModuleNotFoundError: No module named 'user_agent'

**Comment by melbadry9** [comment]
@jamesmiller9048, Make sure to install requirements using 
```shell
 pip3 install -r requirements.txt
```
