### ISSUE TITLE
Issue with Python3.7 in Kali 2020

### ISSUE THREAD

**Issue by tauseefpk** [OWASP/QRLJacking#113]
python3.7 QrlJacker.py

Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Downloads/QRLJacking/QRLJacker/core/browser.py", line 116, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Downloads/QRLJacking/QRLJacker/core/browser.py", line 132, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

[+] Initializing webserver... [whatsapp]

QrlJacker Module(grabber/whatsapp) > Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Downloads/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by anz3lm0** [comment]
Same problem... Is there something to do?

**Comment by RUGMJ7443** [comment]
+1
