### ISSUE TITLE
cannot open firefox.. got error in firefox

### ISSUE THREAD

**Issue by hari2229** [OWASP/QRLJacking#114]
Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Downloads/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Downloads/QRLJacking/QRLJacker/core/browser.py", line 132, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
[!] Couldn't open Firefox! Check the installation instructions again!

**Comment by hari2229** [comment]
p;s help me to solve this...
i have try this by updating firefox, install geckodriver latest version...
but still this error occured
