### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by hamzasaeed2029** [OWASP/QRLJacking#115]
root@server:~/qrl/QRLJacking/QRLJacker# python QrlJacker.py
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/qrl/QRLJacking/QRLJacker/core/Cli.py", line 288
    status(f"Starting interaction with ({cmd.i})...")
                                                   ^
SyntaxError: invalid syntax

**Comment by hamzasaeed2029** [comment]
issue is resolved by upgrading my python version from 3.6 to 3.7.
The framework is designed to work only on python 3.7 or above!
