### ISSUE TITLE
[!] run is not recognized as an internal command !

### ISSUE THREAD

**Issue by RUGMJ7443** [OWASP/QRLJacking#120]
uname -a outputs `Linux raspberrypi 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux`

```
Exception -> __init__() should return None, not 'dict'
    Input -> run
Trackback -> 
Traceback (most recent call last):
  File "/home/pi/QRLJacking/QRLJacker/core/module.py", line 55, in handle
    handler(args)
  File "/home/pi/QRLJacking/QRLJacker/core/module.py", line 135, in command_run
    Settings.headless_browser = browser.headless_browsers()
TypeError: __init__() should return None, not 'dict'
[!] run is not recognized as an internal command !
[+] Maybe you meant : , runreload, refresh, resource
[+] Type help or ? to learn more..

QrlJacker Module(grabber/whatsapp) > 
```

**Comment by RUGMJ7443** [comment]
i will try to run this on a separate machine

**Comment by RUGMJ7443** [comment]
found the issue
