### ISSUE TITLE
failed to start the webserver

### ISSUE THREAD

**Issue by RUGMJ7443** [OWASP/QRLJacking#121]
- [x] ive tried running as root not as root both not working just get this error

```
 QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
[+] Initializing webserver... [whatsapp]

QrlJacker Module(grabber/whatsapp) > Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rugmj/QRLJacking/QRLJacker/core/browser.py", line 143, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rugmj/QRLJacking/QRLJacker/core/browser.py", line 161, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rugmj/QRLJacking/QRLJacker/core/browser.py", line 127, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
```

**Comment by anoopk654** [comment]
I too have the same error.I tried a lot to solve this error but nothing happens

**Comment by anoopk654** [comment]
please help us to solve this
