### ISSUE TITLE
OSError: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by raghubetageri** [OWASP/QRLJacking#131]
Traceback (most recent call last):
  File "/home/raghu/anaconda3/envs/hack/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/raghu/anaconda3/envs/hack/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/raghu/QRLJacking/QRLJacker/core/browser.py", line 164, in serve_module
    webserver.start_serving(host)
  File "/home/raghu/QRLJacking/QRLJacker/core/module_utils.py", line 32, in start_serving
    self.httpd = ReusableTCPServer( (host, self.port), MyHandler)
  File "/home/raghu/anaconda3/envs/hack/lib/python3.7/socketserver.py", line 449, in __init__
    self.server_bind()
  File "/home/raghu/anaconda3/envs/hack/lib/python3.7/socketserver.py", line 463, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address

**Comment by melbadry9** [comment]
You need administration privileges to bind localhost to specific port. 

```bash
sudo pip3 install -r requirements.txt
sudo python3 QrlJacker.py
```

**Comment by raghubetageri** [comment]
i just changed the port and host then it worked
