### ISSUE TITLE
hi i have this erorr, what should i do?

### ISSUE THREAD

**Issue by darkknightt-2002** [OWASP/QRLJacking#133]
Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mmr/QRLJacking/QRLJacker/core/browser.py", line 127, in website_qr
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mmr/QRLJacking/QRLJacker/core/browser.py", line 143, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mmr/QRLJacking/QRLJacker/core/browser.py", line 161, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by djrose305** [comment]
try installing it different ways like pip3 install -r requirements.txt or sudo pip3 install requiremenets.txt or wirh regular pip both ways one wll work and when i launch the program sudo python3 qrlacker.py it works

**Comment by darkknightt-2002** [comment]
> try installing it different ways like pip3 install -r requirements.txt or sudo pip3 install requiremenets.txt or wirh regular pip both ways one wll work and when i launch the program sudo python3 qrlacker.py it works

i tried it but it didn't work,do you have any more ideas?

**Comment by melbadry9** [comment]
Please follow install instruction and check closed issues.

**Comment by darkknightt-2002** [comment]
> Please follow install instruction and check closed issues.

instruction of which part?
