### ISSUE TITLE
STILL can't launch QrlJacker.py !!

### ISSUE THREAD

**Issue by FrisKoo** [OWASP/QRLJacking#135]
root@ipooo:/home/boo/QRLJacking/QRLJacker# sudo python3 QrlJacker.py
Traceback (most recent call last):
  File "/home/boo/QRLJacking/QRLJacker/QrlJacker.py", line 16, in <module>
    from core import Cli,utils,Settings,db
  File "/home/boo/QRLJacking/QRLJacker/core/Cli.py", line 5, in <module>
    from core import utils,db,module,Settings,browser
  File "/home/boo/QRLJacking/QRLJacker/core/module.py", line 4, in <module>
    from core import utils,Settings,Cli,db,browser
  File "/home/boo/QRLJacking/QRLJacker/core/browser.py", line 5, in <module>
    from user_agent import generate_user_agent
ModuleNotFoundError: No module named 'user_agent'

**Comment by umiterkol** [comment]
pip install user_agent

**Comment by melbadry9** [comment]
Make sure to install requirements using `pip3 install -r requirements.txt`
