### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by blackjack704** [OWASP/QRLJacking#139]
QrlJacker Module(grabber/whatsapp) > ----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 50416)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/root/Downloads/QRLJacking/QRLJacker/core/module_utils.py", line 27, in __init__
    super().__init__(*args, directory=serve_dir, **kwargs)
  File "/usr/local/lib/python3.9/http/server.py", line 653, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.9/http/server.py", line 660, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/local/lib/python3.9/http/server.py", line 859, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/local/lib/python3.9/shutil.py", line 208, in copyfileobj
    fdst_write(buf)
  File "/usr/local/lib/python3.9/socketserver.py", line 799, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by blackjack704** [comment]
how to fix this error?
QrlJacker Module(grabber/whatsapp) > ----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 50416)
Traceback (most recent call last):
File "/usr/local/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
self.process_request(request, client_address)
File "/usr/local/lib/python3.9/socketserver.py", line 347, in process_request
self.finish_request(request, client_address)
File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/root/Downloads/QRLJacking/QRLJacker/core/module_utils.py", line 27, in init
super().init(*args, directory=serve_dir, **kwargs)
File "/usr/local/lib/python3.9/http/server.py", line 653, in init
super().init(*args, **kwargs)
File "/usr/local/lib/python3.9/socketserver.py", line 720, in init
self.handle()
File "/usr/local/lib/python3.9/http/server.py", line 427, in handle
self.handle_one_request()
File "/usr/local/lib/python3.9/http/server.py", line 415, in handle_one_request
method()
File "/usr/local/lib/python3.9/http/server.py", line 660, in do_GET
self.copyfile(f, self.wfile)
File "/usr/local/lib/python3.9/http/server.py", line 859, in copyfile
shutil.copyfileobj(source, outputfile)
File "/usr/local/lib/python3.9/shutil.py", line 208, in copyfileobj
fdst_write(buf)
File "/usr/local/lib/python3.9/socketserver.py", line 799, in write
self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by blackjack704** [comment]
can anyone please respond for the above issue!

**Comment by melbadry9** [comment]
I can't reproduce this issue, It's looks like open connection gets closed while serving QR code.  Can you please enable debug mode and send more info about how to reproduce this?

**Comment by blackjack704** [comment]
Thank you for your response, actually I’m very new to Kali Linux , I just followed your steps from YouTube and I made script after finished run command when I’m trying to open the link 0.0.0.0:1337 in Firefox browser before sending to the target. It caused the error broken pipe line.
So as you said I will try to turn on debug mode

**Comment by blackjack704** [comment]
After enable debugging mode, still target can't open the link http://0.0.0.0:1337/

**Comment by melbadry9** [comment]
Follow the following steps that should fix your problem
```bash
sudo pip3 install requirements.txt
sudo python3 QrlJacker.py
```
