### ISSUE TITLE
Whatsapp Key error still persist

### ISSUE THREAD

**Issue by Sqrdelta** [OWASP/QRLJacking#141]
Kali Linux 2021
Lastes firefox version
lastes gecko driver.

**Comment by melbadry9** [comment]
Can you please enable debug mode and provide more details?

**Comment by Fabio-Git-dev** [comment]
@melbadry9  ```<Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
[+] Initializing webserver... [whatsapp]
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run

QrlJacker Module(grabber/whatsapp) > Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/root/Tools/11-Whatsapp_hacks/whatsapp_qr_hack/QRLJacking/QRLJacker/core/browser.py", line 133, in website_qr
  File "/root/Tools/11-Whatsapp_hacks/whatsapp_qr_hack/QRLJacking/QRLJacker/core/browser.py", line 149, in check_img
    controller = self.browsers[module_name]["Controller"]
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
KeyError: 'whatsapp'
    self._target(*self._args, **self._kwargs)
  File "/root/Tools/11-Whatsapp_hacks/whatsapp_qr_hack/QRLJacking/QRLJacker/core/browser.py", line 167, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'
```

**Comment by Fabio-Git-dev** [comment]
@melbadry9  if you want contact me on discord: Fab_#4870

**Comment by Parshuram2** [comment]
same issue. Kali linux 2021. command python3 QrlJacker.py

**Comment by vamos-tech** [comment]
bonjour je suis confronté à un problème dans l'utilisation finale du grabber whatsapp. lorsque je l'execute, voila le message d'erreur  qui s'affiche.  je veux de l'aide 
run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
[+] Initializing webserver... [whatsapp]
  File "/usr/lib/python3.9/threading.py", line 892, in run

    self.run()

**Comment by vamos-tech** [comment]
apres une 2e execution du module whatsapp de QRLJacker, voici l'erreur qui s'affiche :
QrlJacker Module(grabber/whatsapp) >   File "/usr/lib/python3.9/threading.py", line 892, in run
Exception in thread Webserver manager thread:
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "/home/kali_pentest/Documents/QRLJacking/QRLJacker/core/browser.py", line 149, in check_img
    self._target(*self._args, **self._kwargs)
  File "/home/kali_pentest/Documents/QRLJacking/QRLJacker/core/browser.py", line 133, in website_qr
    controller = self.browsers[module_name]["Controller"]
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
KeyError: 'whatsapp'
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali_pentest/Documents/QRLJacking/QRLJacker/core/browser.py", line 167, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'
<Module(grabber/whatsapp) > run
[+] Using the default useragent
[!] Couldn't open Firefox! Check the installation instructions again!

**Comment by vamos-tech** [comment]
au cas quelqu'un a été confronté à ce gens d'erreur et a trouvé une solution, svp qu'il m'aide. merci pour la comprehension

**Comment by N30N-SpH1nX** [comment]
Hey folks, i tried running QRLJacking on Kali Linux but it still keeps ending like this after i run it...

Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/blackforest/QRLJacking/QRLJacker/core/browser.py", line 167, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by Sqrdelta** [comment]
For some reason the dev neither recontacted me on discord, neither kept this opened. What this issue can't be fixed at all because you need to entirely rewrite the script?

**Comment by immortal-007** [comment]
I faced issue while ececuting run coommand

**Comment by immortal-007** [comment]
nope
