### ISSUE TITLE
getting this error\

### ISSUE THREAD

**Issue by Trinadhnaidu** [OWASP/QRLJacking#151]
Traceback (most recent call last):
  File "/root/Desktop/QRLJacking/QRLJacker/QrlJacker.py", line 16, in <module>
    from core import Cli,utils,Settings,db
  File "/root/Desktop/QRLJacking/QRLJacker/core/Cli.py", line 4, in <module>
    import os,sys,time,random,traceback,json,argparse,readline
ModuleNotFoundError: No module named 'readline'

**Comment by melbadry9** [comment]
You need to install `requirements.txt` using `pip3 install -r requirements.txt`

**Comment by Trinadhnaidu** [comment]
Done sir...sir is there any process to undo the whole process from starting
