### ISSUE TITLE
This tool doesn't work anymore!

### ISSUE THREAD

**Issue by nasyx-rakeeb** [OWASP/QRLJacking#174]
It was working very well in v1 but in v2 its a total mess getting this error:

`
QrlJacker > use grabber/whatsapp

< Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
[+] Initializing webserver... [whatsapp]
Exception in thread Webserver manager thread:
Traceback (most recent call last):                                                 File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner

QrlJacker Module(grabber/whatsapp) >     self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/QRLJacking/QRLJacker/core/browser.py", line 149, in check_img
    self._target(*self._args, **self._kwargs)
  File "/home/kali/QRLJacking/QRLJacker/core/browser.py", line 167, in serve_module
    self._target(*self._args, **self._kwargs)
  File "/home/kali/QRLJacking/QRLJacker/core/browser.py", line 133, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
`

**Comment by systemguy** [comment]
same
