### ISSUE TITLE
Session saved successfully

### ISSUE THREAD

**Issue by BimBom123** [OWASP/QRLJacking#175]
if i run QRLJacking comes this:
[+] Got session on whatsapp module
[+] Session saved successfully

but i dont scan the code if i scan the code i only becom a txt on my phone 

if i start with debug mode:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner

[+] Got session on whatsapp module
[+] Profile location saved in profiles/Tue-Jun--7-11:19:47-2022.pf
[+] Session saved successfully
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Desktop/QRLJacking/QRLJacker/core/browser.py", line 170, in serve_module
    webserver.start_serving(host)
  File "/home/kali/Desktop/QRLJacking/QRLJacker/core/module_utils.py", line 32, in start_serving
    self.httpd = ReusableTCPServer( (host, self.port), MyHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by JESSIN7516** [comment]
hi , did you find a solution , I am having the same issue like you ?
