### ISSUE TITLE
QrlJacker Module(grabber/whatsapp) >    run is failed 

### ISSUE THREAD

**Issue by immortal-007** [OWASP/QRLJacking#178]
After entering run command   failed to open 

[+] Using the default useragent

[+] Running a thread to keep the QR image  [whatsapp]
Exception in thread QR updater thread:
[+] Waiting for sessions on whatsapp
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
Exception in thread Idle detector thread:
[+] Initializing webserver... [whatsapp]
Traceback (most recent call last):

QrlJacker Module(grabber/whatsapp) >     self.run()

Exception in thread Webserver manager thread:
  File "/usr/lib/python3.10/threading.py", line 946, in run

QrlJacker Module(grabber/whatsapp) > Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/immortal/Downloads/QRLJacking/QRLJacker/core/browser.py", line 133, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/immortal/Downloads/QRLJacking/QRLJacker/core/browser.py", line 149, in check_img
    self._target(*self._args, **self._kwargs)
  File "/home/immortal/Downloads/QRLJacking/QRLJacker/core/browser.py", line 167, in serve_module
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by immortal-007** [comment]
Anyone here for this solutions
