### ISSUE TITLE
Any one Have solve this problem? 

### ISSUE THREAD

**Issue by MatarEmad** [OWASP/QRLJacking#192]
QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
Exception in thread QR updater thread:
Traceback (most recent call last):
[+] Waiting for sessions on whatsapp
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Downloads/QRLJacking/QRLJacker/core/browser.py", line 133, in website_qr
[+] Initializing webserver... [whatsapp]
Exception in thread Idle detector thread:

QrlJacker Module(grabber/whatsapp) > Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Webserver manager thread:
Traceback (most recent call last):
    self.run()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Downloads/QRLJacking/QRLJacker/core/browser.py", line 149, in check_img
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Downloads/QRLJacking/QRLJacker/core/browser.py", line 167, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by systemguy** [comment]
same bro

**Comment by kali282** [comment]
same here
this happens coz in root firefox cant open & if we tried with virtual then qrljacker said 

Traceback (most recent call last):
  File "/home/kali/Downloads/QRLJacking/QRLJacker/QrlJacker.py", line 59, in <module>
    main()
  File "/home/kali/Downloads/QRLJacking/QRLJacker/QrlJacker.py", line 54, in main
    Cli.start()
  File "/home/kali/Downloads/QRLJacking/QRLJacker/core/Cli.py", line 114, in start
    utils.Input_completer(all_keywords+modules )
  File "/home/kali/Downloads/QRLJacking/QRLJacker/core/utils.py", line 153, in Input_completer
    readline.read_history_file(history_file)
PermissionError: [Errno 13] Permission denied
