### ISSUE TITLE
run is not recognized as an internal command !

### ISSUE THREAD

**Issue by RichardPompeo** [OWASP/QRLJacking#196]
I receive this error when I try to run the "run" command on macos, something to do?
<img width="682" alt="Screenshot 2022-12-14 at 22 08 41" src="https://user-images.githubusercontent.com/65838395/207748545-1841eec8-b515-474a-9f75-56cf333a5d76.png">

**Comment by 4m3k** [comment]
I've the same problem.. This is the debug

QrlJacker > debug
[+] Debug mode enabled!

QrlJacker > use grabber/whatsapp

QrlJacker Module(grabber/whatsapp) > run
Exception -> __init__() should return None, not 'dict'
    Input -> run
Trackback -> 
Traceback (most recent call last):
  File "/Users/lucagarufi/Documents/QRLJacking/QRLJacker/core/module.py", line 55, in handle
    handler(args)
  File "/Users/lucagarufi/Documents/QRLJacking/QRLJacker/core/module.py", line 135, in command_run
    Settings.headless_browser = browser.headless_browsers()
TypeError: __init__() should return None, not 'dict'
[!] run is not recognized as an internal command !
[+] Maybe you meant : , runreload, refresh, resource
[+] Type help or ? to learn more..

I'm on Apple silicon M2 with MacOS Ventura 13.1. Geckodriver works correctly

**Comment by rockstarvibu** [comment]
> I've the same problem.. This is the debug
> 
> QrlJacker > debug [+] Debug mode enabled!
> 
> QrlJacker > use grabber/whatsapp
> 
> QrlJacker Module(grabber/whatsapp) > run Exception -> **init**() should return None, not 'dict' Input -> run Trackback -> Traceback (most recent call last): File "/Users/lucagarufi/Documents/QRLJacking/QRLJacker/core/module.py", line 55, in handle handler(args) File "/Users/lucagarufi/Documents/QRLJacking/QRLJacker/core/module.py", line 135, in command_run Settings.headless_browser = browser.headless_browsers() TypeError: **init**() should return None, not 'dict' [!] run is not recognized as an internal command ! [+] Maybe you meant : , runreload, refresh, resource [+] Type help or ? to learn more..
> 
> I'm on Apple silicon M2 with MacOS Ventura 13.1. Geckodriver works correctly

same issue with apple intel macbook

**Comment by LucaReggiannini** [comment]
Error fixed (see commit https://github.com/OWASP/QRLJacking/pull/203/commits/22d5195f8d084b1d71d7742d0fe216e316b6c92d).
You should download the project again and retry
