### ISSUE TITLE
QRLJacking error while running the framework

### ISSUE THREAD

**Issue by sameer706007** [OWASP/QRLJacking#197]
Hi All,
This is Sameer, a beginner in cyber security, please someone help me in the below issue.
QRLJacking framework is not running, gives an error that "Couldn't open Firefox! Check the installation instructions again!"
Error snapshot is attached below.
![error QRLJacking](https://user-images.githubusercontent.com/122555364/212166254-33c4870d-2d00-4ba3-8c5a-bc0c4b1835c5.png)

**Comment by hiddenfalconscommunity** [comment]
+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
Exception in thread QR updater thread:
[+] Waiting for sessions on whatsapp
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
Exception in thread Idle detector thread:
[+] Initializing webserver... [whatsapp]
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
    self.run()

QrlJacker Module(grabber/whatsapp) >   File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/geoking/QRLJacking/QRLJacker/core/browser.py", line 149, in check_img
Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 892, in run
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/geoking/QRLJacking/QRLJacker/core/browser.py", line 167, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'
    self._target(*self._args, **self._kwargs)
  File "/home/geoking/QRLJacking/QRLJacker/core/browser.py", line 133, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
QrlJacker Module(grabber/whatsapp) >
