### ISSUE TITLE
Run command error

### ISSUE THREAD

**Issue by jayakumar571** [OWASP/QRLJacking#199]
Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 167, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by HasibBinSayed** [comment]
Having this same problem..
