### ISSUE TITLE
QR code not loading

### ISSUE THREAD

**Issue by rockstar0050** [OWASP/QRLJacking#200]
Hi I am getting below logs and the QR code is not loading. Could anyone please help me.

QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button
[whatsapp]
[+] Initializing webserver... [whatsapp]
 QrlJacker Module(grabber/whatsapp) > ----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 43532)
Traceback (most recent call last):
File "/usr/lib/python3.10/http/server.py", line 727, in send_head
f = open(path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/rockstar005
Downloads/QRLJacking/QRLJacker/core/www/whatsapp/tmp.png'
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
self.process_request(request, client_address)
File "/usr/lib/python3.10/socketserver.py", line 347, in process_request
self.finish_request(request, client_address)
File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/home/rockstar005/Downloads/QRLJacking/QRLJacker/core
module_utils.py", line 27, in __init__
super().__init__(*args, directory=serve_dir, **kwargs)
File "/usr/lib/python3.10/http/server.py", line 668, in __init__
super().__init__(*args, **kwargs)
File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
self.handle()
File "/usr/lib/python3.10/http/server.py", line 433, in handle
self.handle_one_request()
File "/usr/lib/python3.10/http/server.py", line 421, in handle_one_request
method()
File "/usr/lib/python3.10/http/server.py", line 672, in do_GET
f = self.send_head()
File "/usr/lib/python3.10/http/server.py", line 729, in send_head
self.send_error(HTTPStatus.NOT_FOUND, "File not found")File "/usr/lib/python3.10/http/server.py", line 488, in send_error
self.wfile.write(body)
File "/usr/lib/python3.10/socketserver.py", line 826, in write
self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
  QrlJacker Module(grabber/whatsapp) >

**Comment by vinniepie** [comment]
![IMG_20230202_140953.jpg](https://user-images.githubusercontent.com/85624056/216592835-086fd430-6129-486d-bce6-28a51b952145.jpg)

Same here...

**Comment by husshuss179** [comment]
same here

did u find a solution?

> ![IMG_20230202_140953.jpg](https://user-images.githubusercontent.com/85624056/216592835-086fd430-6129-486d-bce6-28a51b952145.jpg)
> 
> Same here...

**Comment by rockstar0050** [comment]
Not yet.

**Comment by rockstar0050** [comment]
No Yet

**Comment by vinniepie** [comment]
I Will try it on my other laptop. 
I have this problem with kali x86
My other laptop is x64 based. 
I wil try it there... For now i have no solution :/

**Comment by vinniepie** [comment]
> same here
> 
> did u find a solution?
> 
> > ![IMG_20230202_140953.jpg](https://user-images.githubusercontent.com/85624056/216592835-086fd430-6129-486d-bce6-28a51b952145.jpg)
> > 
> > Same here...
> 
> 

![IMG_20230204_120851.jpg](https://user-images.githubusercontent.com/85624056/216763983-5d4e8ff4-a766-4356-8dfb-c55366157092.jpg)

Geckodrivers are updated yesterday. 
Try to Install the update, en try to run again (:

**Comment by husshuss179** [comment]
> > same here
> > did u find a solution?
> > > ![IMG_20230202_140953.jpg](https://user-images.githubusercontent.com/85624056/216592835-086fd430-6129-486d-bce6-28a51b952145.jpg)
> > > Same here...
> 
> ![IMG_20230204_120851.jpg](https://user-images.githubusercontent.com/85624056/216763983-5d4e8ff4-a766-4356-8dfb-c55366157092.jpg)
> 
> Geckodrivers are updated yesterday. Try to Install the update, en try to run again (:

im travelling at the moment and i dont have my laptop 
can you try it ?
tell me if it worked.

**Comment by vinniepie** [comment]
> > > same here
> > > did u find a solution?
> > > > ![IMG_20230202_140953.jpg](https://user-images.githubusercontent.com/85624056/216592835-086fd430-6129-486d-bce6-28a51b952145.jpg)
> > > > Same here...
> > 
> > ![IMG_20230204_120851.jpg](https://user-images.githubusercontent.com/85624056/216763983-5d4e8ff4-a766-4356-8dfb-c55366157092.jpg)
> > 
> > Geckodrivers are updated yesterday. Try to Install the update, en try to run again (:
> 
> im travelling at the moment and i dont have my laptop 
> can you try it ?
> tell me if it worked.

Same issue on x64 version of Kali Linux. 
I'm now trying it with Ubuntu.

**Comment by rockstar0054** [comment]
any update guys.

**Comment by LucaReggiannini** [comment]
I think that the code is outdated. I see 3 problems:

1. the **xpath** for the images on Whatsapp page seems changed: file "QRLJacker/core/modules/grabber/whatsapp.py" must be updated

3. the code uses method "Screenshot" in "QRLJacking/QRLJacker/core/module_utils.py" to get the screenshot of the entire page. Later it uses xpath to find QR Code location/size and uses this information to crop the QR from the screenshot. The problem is that the method "Screenshot" throws an error: **'WebDriver' object has no attribute 'find_elements_by_xpath'**. This error should be caused by the fact that "find_elements_by_xpath" is deprecated in newer version of Selenium (see https://github.com/SeleniumHQ/selenium/blob/a4995e2c096239b42c373f26498a6c9bb4f2b3e7/py/CHANGES) so we need to consider another method (maybe ".find_element", see https://selenium-python.readthedocs.io/locating-elements.html)

5. the QR Code image is saved as "full.png" but the default template is looking for "tmp.png"

I don't know if there is anything else to be fixed at the moment.

I don't know if this project is dead: is there anyone who want to fix this?
I will try (slowly cause lack of time) to update the code and make a pull request.
If no one is watching this project i will fork it and update it in another repo.

**Comment by LucaReggiannini** [comment]
Found and fixed other problems that prevents the program from working correctly. I'm going to update my forked repo in a couple of days and submit a pull request

**Comment by vinniepie** [comment]
Very nice 😄👌

**Comment by SymbianSyMoh** [comment]
Hello @LucaReggiannini, Sorry for not replying back in time, I would like to thank you a lot for your efforts, once you make the PR and everything goes well please reach out to me to add you as a maintainer because most of the maintainers are so busy in the meantime.

**Comment by LucaReggiannini** [comment]
Hello everybody. Working on: https://github.com/LucaReggiannini/QRLJacking
Seems like QRLJacker is working again. Tested on:
```
kali@kali:~/Downloads/QRLJacking/QRLJacker$ uname -a && python --version
Linux kali 6.1.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1kali2 (2023-02-23) x86_64 GNU/Linux
Python 3.11.2
```
This specific issue was about Whatsapp so i actually tested/fixed the code for the Whatsapp grabber.
Before submitting the pull request i will try the code on a Windows machine.
Meanwhile feel free to see/test the changes.
Any criticism is welcome.

**Comment by LucaReggiannini** [comment]
@SymbianSyMoh Thanks for the merge. If you want I can help keeping it up to date

**Comment by bernarrdgnazou** [comment]
Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
[+] Initializing webserver... [whatsapp]

QrlJacker Module(grabber/whatsapp) > Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/artemix/Hacking_tools/QRLJacking/QRLJacker/core/browser.py", line 198, in serve_module
    webserver.start_serving(host)
  File "/home/artemix/Hacking_tools/QRLJacking/QRLJacker/core/module_utils.py", line 33, in start_serving
    self.httpd = ReusableTCPServer( (host, self.port), MyHandler)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by krlabs** [comment]
Problem still actual.

**Comment by arjeeeen** [comment]
> Hello everybody. Working on: https://github.com/LucaReggiannini/QRLJacking Seems like QRLJacker is working again. Tested on:
> 
> ```
> kali@kali:~/Downloads/QRLJacking/QRLJacker$ uname -a && python --version
> Linux kali 6.1.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1kali2 (2023-02-23) x86_64 GNU/Linux
> Python 3.11.2
> ```
> 
> This specific issue was about Whatsapp so i actually tested/fixed the code for the Whatsapp grabber. Before submitting the pull request ~i will try the code on a Windows machine~. Meanwhile feel free to see/test the changes. Any criticism is welcome.
> 
> Edit: sorry i was tricked by the OS check message
> 
> ```python
> elif os.name=="nt":
>     error("The framework is designed to work on linux or windows only! Sorry for that :)")
> ```
> 
> Fixed this typo. I actually tested the code on MacOS Monterey and fixed some other bug. The problem now is that i can't fully test the framework on MacOS because Firefox is not displaying the QRCode on Whatsapp Web page: i think i miss hardware acceleration because the system is installed on a virtual machine (tried Homebrew and native App without any luck). I will make the pull request in hope that someone with a Macintosh can test the changes.

Ciao Luca, hai risolto definitivamente? Perchè purtroppo il problema persiste

**Comment by rizwanreshi081** [comment]
![qr](https://github.com/OWASP/QRLJacking/assets/86390397/488427a6-249c-42e7-8151-6960af446b2c)
QR code not generating, can anyone tell me what seems to be the problem.

**Comment by coliovacruz** [comment]
Apparently the "tmp.png" file is not generated and when the html code tries to search, it does not exist in the folder. Any way to fix this?

**Comment by Ancientech01** [comment]
This is 2024......i am encountering the same issue. is it that the project is dead?

**Comment by Ancientech01** [comment]
> Apparently the "tmp.png" file is not generated and when the html code tries to search, it does not exist in the folder. Any way to fix this?

please have you been able to find a solution?

**Comment by Rocky-341** [comment]
Can anyone suggest a solution for this error

QrlJacker > refresh
[+] Database updated! ( 1 module(s) loaded now )

QrlJacker > reload
[+] Database updated! ( 1 module(s) loaded now )

QrlJacker > use grabber/whatsapp

QrlJacker Module(grabber/whatsapp) > show

 Name              Description                                 
 grabber/whatsapp  Whatsapp QR-sessions grabber and controller 

QrlJacker Module(grabber/whatsapp) > options

 Name       Current value  Required  Description                                                                                 
 port       80             Yes       The local port to listen on.                                                                
 host       0.0.0.0        Yes       The local host to listen on.                                                                
 useragent  (default)      Yes       Make useragent is the (default) one, a (random) generated useragent or a specifed useragent 

QrlJacker Module(grabber/whatsapp) > set port 1337
[+] port => 1337

QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
[+] Initializing webserver... [whatsapp]

QrlJacker Module(grabber/whatsapp) > options

 Name       Current value  Required  Description                                                                                 
 port       1337           Yes       The local port to listen on.                                                                
 host       0.0.0.0        Yes       The local host to listen on.                                                                
 useragent  (default)      Yes       Make useragent is the (default) one, a (random) generated useragent or a specifed useragent 

QrlJacker Module(grabber/whatsapp) > sessions
[!] No captured sessions.

QrlJacker Module(grabber/whatsapp) > ----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 56434)
Traceback (most recent call last):
  File "/usr/lib/python3.12/http/server.py", line 731, in send_head
    f = open(path, 'rb')
        ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/rakesh/Downloads/QRLJacking/QRLJacker/core/www/whatsapp/favicon.ico'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.12/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/rakesh/Downloads/QRLJacking/QRLJacker/core/module_utils.py", line 28, in __init__
    super().__init__(*args, directory=serve_dir, **kwargs)
  File "/usr/lib/python3.12/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/lib/python3.12/http/server.py", line 676, in do_GET
    f = self.send_head()
        ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/server.py", line 733, in send_head
    self.send_error(HTTPStatus.NOT_FOUND, "File not found")
  File "/usr/lib/python3.12/http/server.py", line 491, in send_error
    self.wfile.write(body)
  File "/usr/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------

**Comment by MuhammedEnesGurkan** [comment]
under /home/kali/tools/qr/qr/QRLJacking/QRLJacker/core/modules/grabber folder. Change xpaths for your whatsapp and save it. And rerun the code.

**Comment by Mans31** [comment]
Good day, QR is not generated for me either, is there a solution? I opened the directory /home/kali/QRLJacking/QRLJacker/core/modules/ there are files whatsapp.py and _init__.py as you said MuhammedEnesGurkan, I would like to clarify what exactly needs to be changed? Can you please help
