### ISSUE TITLE
QR code not loading

### ISSUE THREAD

**Issue by hak98** [OWASP/QRLJacking#202]
QR Code not loading in firefox or another browser. When enabling debug and running the code whatsapp "add device" code pops up but it is not the attack it is directly from whats app. 
<ule(grabber/whatsapp) > debug
[+] Debug mode enabled!

<ule(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
[+] Initializing webserver... [whatsapp]

<ule(grabber/whatsapp) >

**Comment by hak98** [comment]
QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
[+] Initializing webserver... [whatsapp]

QrlJacker Module(grabber/whatsapp) > sessions
[!] No captured sessions.

QrlJacker Module(grabber/whatsapp) > ----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 48250)
Traceback (most recent call last):
  File "/usr/lib/python3.10/http/server.py", line 717, in send_head
    f = open(path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/root/Downloads/QRLJacking/QRLJacker/core/www/whatsapp/tmp.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/root/Downloads/QRLJacking/QRLJacker/core/module_utils.py", line 27, in __init__
    super().__init__(*args, directory=serve_dir, **kwargs)
  File "/usr/lib/python3.10/http/server.py", line 658, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/usr/lib/python3.10/http/server.py", line 662, in do_GET
    f = self.send_head()
  File "/usr/lib/python3.10/http/server.py", line 719, in send_head
    self.send_error(HTTPStatus.NOT_FOUND, "File not found")
  File "/usr/lib/python3.10/http/server.py", line 487, in send_error
    self.wfile.write(body)
  File "/usr/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------

**Comment by 0YunusHasan** [comment]
i have also the same problem did you find the solution?

**Comment by Derosarie** [comment]
Code QR

**Comment by krlabs** [comment]
if open localhost:port, QR dont loading, but in automatic selenium browser web.whatsapp.com displaying original page web.whatsapp with qr code.
