### ISSUE TITLE
bug in open firefox

### ISSUE THREAD

**Issue by descontrol123** [OWASP/QRLJacking#218]
![Captura de pantalla (447)](https://github.com/OWASP/QRLJacking/assets/117747051/1ce2e5c5-5609-4ae7-bb78-aa59acb50f24)
hello, someone was able to solve the problem with the geckodriver in firefox since I did it correctly in kali purple and it does not allow me to execute it, I don't know if it can be seen in the image but it tells me
1. "using the default user agent"
2. "couldn't open firefox! check the installation instructions again!"
and then I followed the steps as I repeat and the same thing appears to me, if someone could help me please or if the creator could it would be great :) thanks

**Comment by LucaReggiannini** [comment]
Hello, can you please run the following commands and post the output?

```
file /usr/local/share/geckodriver
ls -al /usr/local/share/geckodriver
which firefox
firefox --version
```

**Comment by hemanthreddiee** [comment]
I also had the same issue. 

Just downgrade selenium using 
$ pip install selenium==4.9.0

Hope this works.

**Comment by descontrol123** [comment]
![Captura de pantalla (453)](https://github.com/OWASP/QRLJacking/assets/117747051/1a3ebc72-9df8-445d-9703-1ee2af993bad)
hello it appears like this and I have the most recent version of firefox

**Comment by LucaReggiannini** [comment]
> Hello, can you please run the following commands and post the output?
> 
> ```
> file /usr/local/share/geckodriver
> ls -al /usr/local/share/geckodriver
> which firefox
> firefox --version
> ```

Please, try this

**Comment by descontrol123** [comment]
> 
![Captura de pantalla 2023-07-20 152917](https://github.com/OWASP/QRLJacking/assets/117747051/fb5d86f9-825a-4581-8cef-c8d9c6eade94)
there it is friend

**Comment by LucaReggiannini** [comment]
> > 
> 
> ![Captura de pantalla 2023-07-20 152917](https://user-images.githubusercontent.com/117747051/254988978-fb5d86f9-825a-4581-8cef-c8d9c6eade94.png) there it is friend

Seems like you downloaded the wrong gecko version: i see "aarch64" (for ARM) processor but probably you need the x64 version for Linux.
You may need this https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz

**Comment by descontrol123** [comment]
![Captura de pantalla 2023-07-21 214827](https://github.com/OWASP/QRLJacking/assets/117747051/ff32c827-1ccf-4ca9-bbf4-c56413d46f35)
The same friend, look, I installed what you sent me and I put selenium 4.9.0 in it and I put the command use grabber/whatsapp and nothing appears. What else could it be?

**Comment by LucaReggiannini** [comment]
It is normal if nothing happens: when you run QRLJacker it will spawn an invisible Selenium (Firefox) instance and starts listening on the local port you set with `set port` command (for example `set port 8080`) if you connect to, for example, `localhost:8080` with your browser you will see the phishing page correctly. Let me know if the problem is fixed

**Comment by ZiadGad** [comment]
> I also had the same issue.
> 
> Just downgrade selenium using $ pip install selenium==4.9.0
> 
> Hope this works.

It Works For me

**Comment by dey-joydeep** [comment]
@LucaReggiannini 

Can you please help with this error

```
QrlJacker > use grabber/whatsapp

QrlJacker Module(grabber/whatsapp) > set port 3200
[+] port => 3200

QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
 Exception: Message: Process unexpectedly closed with status 1

 Trackback: 
Traceback (most recent call last):
  File "/home/jds/Downloads/QRLJacking/QRLJacker/core/browser.py", line 76, in new_session
    new_headless[module_name]["Controller"] = Firefox(profile, executable_path="/usr/local/share/geckodriver", capabilities=caps)#options=self.opts) # Inserting the browser object
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/firefox/webdriver.py", line 201, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

[!] Couldn't open Firefox! Check the installation instructions again!

QrlJacker Module(grabber/whatsapp) > 
```

**Comment by LucaReggiannini** [comment]
@dey-joydeep can you please repeat the following steps made by other users in this thread?

Commands:

> > Hello, can you please run the following commands and post the output?
> > ```
> > file /usr/local/share/geckodriver
> > ls -al /usr/local/share/geckodriver
> > which firefox
> > firefox --version
> > ```
> 
> Please, try this

Run the commands and post the output here

**Comment by anarhia01** [comment]
(.venv) [castrv@castrv phish]$ file /usr/local/share/geckodriver
/usr/local/share/geckodriver: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, BuildID[sha1]=204c340e375aa3e0fd8a9fa16ee94460221f8f1e, with debug_info, not stripped
(.venv) [castrv@castrv phish]$ ls -al /usr/local/share/geckodriver
-rwxr-xr-x. 1 castrv castrv 9710704 апр  3 00:59 /usr/local/share/geckodriver
(.venv) [castrv@castrv phish]$ which firefox
/usr/bin/firefox
(.venv) [castrv@castrv phish]$ firefox --version
Mozilla Firefox 116.0.3

**Comment by hamzasakhicyber** [comment]
> @dey-joydeep can you please repeat the following steps made by other users in this thread?
> 
> Commands:
> 
> > > Hello, can you please run the following commands and post the output?
> > > ```
> > > file /usr/local/share/geckodriver
> > > ls -al /usr/local/share/geckodriver
> > > which firefox
> > > firefox --version
> > > ```
> > 
> > 
> > Please, try this
> 
> Run the commands and post the output here

                                                                                                                                                           
┌──(kali㉿kali)-[~/Desktop/Andro_Tools]
└─$ file /usr/local/share/geckodriver
ls -al /usr/local/share/geckodriver
which firefox
firefox --version

/usr/local/share/geckodriver: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, BuildID[sha1]=204c340e375aa3e0fd8a9fa16ee94460221f8f1e, with debug_info, not stripped
-rwxr-xr-x 1 kali kali 9710704 Apr  2 17:59 /usr/local/share/geckodriver
/usr/bin/firefox
Mozilla Firefox 115.1.0esr

**Comment by hamzasakhicyber** [comment]
Kindly help me to fix it.

**Comment by hamzasakhicyber** [comment]
I have fixed it, Just used the given command to give root privileges to the firefox.
 
chown root:root /home/kali/.Xauthority

**Comment by Raxuis** [comment]
> @dey-joydeep can you please repeat the following steps made by other users in this thread?
> 
> Commands:
> 
> > > Hello, can you please run the following commands and post the output?
> > > ```
> > > file /usr/local/share/geckodriver
> > > ls -al /usr/local/share/geckodriver
> > > which firefox
> > > firefox --version
> > > ```
> > 
> > 
> > Please, try this
> 
> Run the commands and post the output here

/usr/local/share/geckodriver: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, BuildID[sha1]=204c340e375aa3e0fd8a9fa16ee94460221f8f1e, with debug_info, not stripped
-rwxr-xr-x 1 raphael raphael 9710704 Apr  2 23:59 /usr/local/share/geckodriver                                                                            
/usr/bin/firefox
zsh: exec format error: firefox

**Comment by dileep-2002** [comment]
> 

thanks bro it works for my system

**Comment by Tougharah** [comment]
![Qrljacker](https://github.com/OWASP/QRLJacking/assets/73382990/d2d39fa5-416a-4c51-b53c-4a3a262647e8)

Help me fix that Firefox problem please

**Comment by lunaal48** [comment]
> It is normal if nothing happens: when you run QRLJacker it will spawn an invisible Selenium (Firefox) instance and starts listening on the local port you set with `set port` command (for example `set port 8080`) if you connect to, for example, `localhost:8080` with your browser you will see the phishing page correctly. Let me know if the problem is fixed


Hello, i am having the same problem. Did all what you guys said. Checked the version, downgraded selenium but the same problem kept occuring. Will you please elaborate on this solution that you provided above?

**Comment by dileep-2002** [comment]
> Hello, can you please run the following commands and post the output?
> 
> ```
> file /usr/local/share/geckodriver
> ls -al /usr/local/share/geckodriver
> which firefox
> firefox --version
> ```
![Screenshot (409)](https://github.com/OWASP/QRLJacking/assets/113206802/7e16e724-3fb2-4db3-8d94-86e675729816)

**Comment by dileep-2002** [comment]
![Screenshot (410)](https://github.com/OWASP/QRLJacking/assets/113206802/c938071d-c36c-4a57-9973-fa147c062aa7)







again i got this error

**Comment by dileep-2002** [comment]
can anyone please slove this and help me

**Comment by moisha0007** [comment]
![Screenshot 2024-03-13 230038](https://github.com/OWASP/QRLJacking/assets/161302048/65fcf26b-9d64-4b85-8f67-4df194290e7e)
please help me !!

**Comment by Git-Utkarsh** [comment]
============================[SOLVED]=====================================
Geckodriver Version === >  https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz

$ sudo su
$ pip3 install selenium==4.9.0    
$ chown root:root /home/kali/.Xauthority	# Root Permissions to Firefox
$ python3 QrlJacker.py				# Using python 3.11

**Comment by arit98** [comment]
![Image](https://github.com/user-attachments/assets/c66a33b5-6d99-46f6-a90f-cb77b6c875c8)

I am waiting for sins 2 months
anybody help me
