### ISSUE TITLE
QR code cannot be loaded

### ISSUE THREAD

**Issue by mack-king** [OWASP/QRLJacking#249]
![image](https://github.com/user-attachments/assets/f6664678-e4f9-431d-ab06-3cd3ba55108e)
I also faced the same problem, tmp.png was missing in www/whatsapp, I added the file manually. However, the QR code still cannot be loaded after startup.
Exception in thread Wlebserver manager thread:Traceback (most recent call last):File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_innerself.run()File "/usr/lib/python3.7/threading.py", line 870, in runself._target(*self._args, self._kwargs)File "/home/kali/QRLJacking/QRLJacker/core/browser.py", line 198, in serve_modulewebserver,start_serving(host) .File "/home/kali/QRLJacking/QRLJacker/core/module_utils.py", line 33, in startservingself,httpd =ReusableTCPServer((host, self,port),MyHandler)File "/usr/lib/python3.7/socketserver.py", line 452, in ___init__self,server_bind()File "/usr/lib/python3.7/socketserver,py", line 466, in server_bindself.socket.bind(self.server _address)'… rwu,OSError: [Errno 98] Address already in use

**Comment by mack-king** [comment]
@SymbianSyMoh
@D4Vinci
@ShawkyZ
@LucaReggiannini
@yipalber
@aethmos
@KamalAwasthi
@fiberghost
@sameersingh7
ubuntu 20.04 ,geckodriver 035，Who can help me solve this problem. Thank you so much.

**Comment by levo-777** [comment]
I made a similar tool, can you try it out and give me feedback pls

https://github.com/levo-777/whats_app_qr_code_phisher
