### ISSUE TITLE
Error launching the module

### ISSUE THREAD

**Issue by AlainChaaya** [OWASP/QRLJacking#40]
OS name: Kali GNU/Linux Rolling
OS type: 64-bit
Version: Version 3.30.2
Python Version: 3.7
FireFox Version: 60.4.0esr (64-bit)

The whole installation process appeared to be correct since I followed the instructions from this link: https://github.com/OWASP/QRLJacking/tree/master/QRLJacker

Then to run the attack i wrote down these codes and appeared to have some errors when i write the "run" command after setting the port as you can see here:

<Module(grabber/whatsapp) > set port 1337
[+] port => 1337

<Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
[+] Initializing webserver... [whatsapp]

QrlJacker Module(grabber/whatsapp) > Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 135, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 107, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 120, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

I have to manually exit because nothing appears after that (using CTRL+C)

I tried rerunning "run" and got this message:
[+] Using the default useragent
[!] Couldn't open Firefox! Check the installation instructions again!
 
I don't know what's wrong with my firefox tho...
Any kind of help would be very much appreciated!

**Comment by manan2501** [comment]
I have the same problem. :(

**Comment by D4Vinci** [comment]
It's the same issue in #37 
Try updating your Firefox to version 66 which is the latest and it's working with me

**Comment by D4Vinci** [comment]
Closed due to duplication. see #37

**Comment by jepunband** [comment]
i have the same problem. hi have geckodriver and the latest firefox 66. still got error

Exception in thread QR updater thread:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/home/hol/Tools/QRLJacking/QRLJacker/core/browser.py", line 116, in website_qr
controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

QrlJacker Module(grabber/whatsapp) > Exception in thread Idle detector thread:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/home/hol/Tools/QRLJacking/QRLJacker/core/browser.py", line 132, in check_img
controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Webserver manager thread:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/home/hol/Tools/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by azamet90** [comment]
same +

**Comment by Kelvin360-uk** [comment]
same

**Comment by immortal-007** [comment]
QrlJacker Module(grabber/whatsapp) > run
[+] Using useragent default
[!] Couldn't open Firefox! Check the installation instructions again!

**Comment by immortal-007** [comment]
QrlJacker Module(grabber/whatsapp) > run
[+] Using useragent default
[!] Couldn't open Firefox! Check the installation instructions again!

**Comment by kalideneo** [comment]
QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
[!] Couldn't open Firefox! Check the installation instructions again!
