### ISSUE TITLE
Error running whatsapp module

### ISSUE THREAD

**Issue by AlainChaaya** [OWASP/QRLJacking#44]
Using python3.7 
Using firefox66
Installed QRLJacker using the installation guide

When i run after setting port 1337 i get this error (debug mode and report mode enabled)

<Module(grabber/whatsapp) > run
[+] Using the default useragent
 Exception: Message: Unable to find a matching set of capabilities

 Trackback: 
Exception -> name 'traceback' is not defined
    Input -> run
Trackback -> 
Traceback (most recent call last):
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 61, in new_session
    new_headless[module_name]["Controller"] = Firefox(profile)#options=self.opts) # Inserting the browser object
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/QRLJacking/QRLJacker/core/module.py", line 55, in handle
    handler(args)
  File "/root/QRLJacking/QRLJacker/core/module.py", line 139, in command_run
    current_browser = Settings.headless_browser.new_session(exec_info.name, exec_info.url, global_options["useragent"][2])
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 68, in new_session
    traceback.print_exc()
NameError: name 'traceback' is not defined
[!] run is not recognized as an internal command !
[+] Maybe you meant : , runreload, refresh, resource
[+] Type help or ? to learn more..

**Comment by thetruegeek** [comment]
Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Desktop/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Desktop/QRLJacking/QRLJacker/core/browser.py", line 116, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Desktop/QRLJacking/QRLJacker/core/browser.py", line 132, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

**Comment by AlainChaaya** [comment]
So there is no solution to this problem?

**Comment by jepunband** [comment]
here is the same issue with debug mode enabled.

[+] Using the default useragent
 Exception: Message: invalid argument: can't kill an exited process

 Trackback: 
Exception -> name 'traceback' is not defined
    Input -> run
Trackback -> 
Traceback (most recent call last):
  File "/home/hol/Tools/QRLJacking/QRLJacker/core/browser.py", line 61, in new_session
    new_headless[module_name]["Controller"] = Firefox(profile)#options=self.opts) # Inserting the browser object
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hol/Tools/QRLJacking/QRLJacker/core/module.py", line 55, in handle
    handler(args)
  File "/home/hol/Tools/QRLJacking/QRLJacker/core/module.py", line 137, in command_run
    Settings.headless_browser.new_session(exec_info.name, exec_info.url, global_options["useragent"][2])
  File "/home/hol/Tools/QRLJacking/QRLJacker/core/browser.py", line 68, in new_session
    traceback.print_exc()
NameError: name 'traceback' is not defined

**Comment by sagar01234** [comment]
I am also getting same error can you please anyone assist on this

**Comment by D4Vinci** [comment]
I just made a hotfix for it. Try it now and tell me what's the output.

**Comment by jepunband** [comment]
still getting the same errors .. 


QrlJacker Module(grabber/whatsapp) > Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hol/Tools/QRLJacking/QRLJacker/core/browser.py", line 116, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hol/Tools/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hol/Tools/QRLJacking/QRLJacker/core/browser.py", line 132, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

**Comment by D4Vinci** [comment]
See issue #37 this is because you can't run firefox as root in a user session so either install the framework as a user and run it as a user or switch to root session and run it.
Closed due to duplication, reopen if the problem persists.
