### ISSUE TITLE
 Exception in thread Webserver manager thread: Traceback 

### ISSUE THREAD

**Issue by thetruegeek** [OWASP/QRLJacking#46]
Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Desktop/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Desktop/QRLJacking/QRLJacker/core/browser.py", line 116, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Desktop/QRLJacking/QRLJacker/core/browser.py", line 132, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

**Comment by desti8383** [comment]
I have the same problem now....
**pleas** help....**

**Comment by jepunband** [comment]
hi i have geckodriver installed and my firefox is the latest is firefox quantum 66.
when i "run" it, i get errors:

Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jeret/Tools/QRLJacking/QRLJacker/core/browser.py", line 116, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'


QrlJacker Module(grabber/whatsapp) > Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jeret/Tools/QRLJacking/QRLJacker/core/browser.py", line 132, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jeret/Tools/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by jepunband** [comment]
have geckodriver & the latest firefox 66.

Exception in thread QR updater thread:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/home/hol/Tools/QRLJacking/QRLJacker/core/browser.py", line 116, in website_qr
controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

QrlJacker Module(grabber/whatsapp) > Exception in thread Idle detector thread:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/home/hol/Tools/QRLJacking/QRLJacker/core/browser.py", line 132, in check_img
controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Webserver manager thread:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/home/hol/Tools/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by D4Vinci** [comment]
This error will happen only if you ran the debug mode and after the browser appeared you closed it by yourself so now the framework can't communicate with the browser!
**Solution: don't use debug mode if you don't need it** :smile:

**Comment by kamiodumb** [comment]
Sir i'm needin' your help, i'm in same situation that '' jepunband commented on May 13'' u said to her that Solution: don't use debug mode if you don't need it smile, i wanna know how can i go out debug mode i'm needin' much ur help thx u sir have a good a day.

**Comment by rasyidcode** [comment]
For those who still encounter this problem, try to set the host to your localhost 127.0.0.1 or your ip address in your network for example 192.168.1.X, and don't forget to set the port

**Comment by GSri30** [comment]
Yea..It perfectly works fine using local host, but it's not the thing we needed..right. Whats the use running over our local host !!
I just have a doubt..does this script also depend upon the version of kali we are using?

**Comment by GSri30** [comment]
Yea..It perfectly works fine using local host, but it's not the thing we needed..right. For example in my case, It's not sufficient to run over only on my localhost..So is there anything we are missing?
I just have a doubt..does this script also depend upon the version of kali we are using?

**Comment by Cthacker200** [comment]
python -m pip install pyaudio
pip install tf-models-official
pip install djoser
export PYTHONPATH=$PYTHONPATH:/path/tomy/tf_models
py -m pip install # sit module in cmd
pip install 'modulename'

Problem solved, have a good day.
