### ISSUE TITLE
can't launch QrlJacker.py

### ISSUE THREAD

**Issue by vrutang** [OWASP/QRLJacking#48]
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 288
    status(f"Starting interaction with ({cmd.i})...")
                                                   ^
SyntaxError: invalid syntax

**Comment by pan-mori** [comment]
hi, probably you have wrong install requirements in to python. I have same problem. for my solution is "python3.7 /usr/bin/pip3 install -r requirements.txt"

**Comment by vrutang** [comment]
not working in my case

**Comment by ronitprajapati** [comment]
i have also same problem please tell me a solution. i think some coding is wrong in cli.py file

**Comment by ankushyoyo** [comment]
I think you installed wrong version of python
Use python 3.7 to execute this script

**Comment by ronitprajapati** [comment]
can we talk on video call plzzzz solve my problem i still want to learn this attack

**Comment by ronitprajapati** [comment]
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 288
    status(f"Starting interaction with ({cmd.i})...")

**Comment by jeretc** [comment]
it's python3, so the command is "sudo python3 QrlJacker.py" . make sure python3 is installed.

**Comment by D4Vinci** [comment]
you are not using python 3.7 that's the problem. If you have multiple versions use python3.7 instead of python3

**Comment by FrisKoo** [comment]
root@***:/home/***/QRLJacking/QRLJacker# sudo python3 QrlJacker.py
Traceback (most recent call last):
  File "/home/bico/QRLJacking/QRLJacker/QrlJacker.py", line 16, in <module>
    from core import Cli,utils,Settings,db
  File "/home/bico/QRLJacking/QRLJacker/core/Cli.py", line 5, in <module>
    from core import utils,db,module,Settings,browser
  File "/home/bico/QRLJacking/QRLJacker/core/module.py", line 4, in <module>
    from core import utils,Settings,Cli,db,browser
  File "/home/bico/QRLJacking/QRLJacker/core/browser.py", line 5, in <module>
    from user_agent import generate_user_agent
ModuleNotFoundError: No module named 'user_agent'
