### ISSUE TITLE
How to solve this problem 

### ISSUE THREAD

**Issue by Anonymous2806** [OWASP/QRLJacking#63]
Trackback ->
Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/home/OWASP-QRLJacking_-_2019-04-09_09-40-26/QRLJacker/core/browser.py", line 107, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

**Comment by D4Vinci** [comment]
See pinned issue #37
