### ISSUE TITLE
KeyError: whatsapp

### ISSUE THREAD

**Issue by horton4** [OWASP/QRLJacking#74]
I got this error if anybody could help me fix this I would be really really happy...

<Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
[+] Initializing webserver... [whatsapp]

QrlJacker Module(grabber/whatsapp) > Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 116, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 132, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by horton4** [comment]
System is Kali Linux Raspberry Pi 3B+

**Comment by D4Vinci** [comment]
See #37

**Comment by sr624** [comment]
Whenever i run qrljaking .it's see error key whatsapp

**Comment by Cthacker200** [comment]
Please help i get the following error controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

**Comment by dileep-2002** [comment]
Please help Mee how to solve it man
