### ISSUE TITLE
Problem when I try to give the comand Run

### ISSUE THREAD

**Issue by frankota** [OWASP/QRLJacking#75]
I am having a problem qhen I give the run comand for QRLJacking
Here below I report the result of options comand:
Name       Current value  Required  Description                                                                                 
 port       3137           Yes       The local port to listen on.                                                                
 host       127.0.0.0      Yes       The local host to listen on.                                                                
 useragent  (default)      Yes       Make useragent is the (default) one, a (random) generated useragent or a specifed useragent 
The result of firefox -v is Mozilla Firefox 71.0
The error whe I give the comand run is listed here:
```
+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 116, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 132, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

[+] Initializing webserver... [whatsapp]
Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

```
If I try the comand run for the second time the error is :
```
[+] Using the default useragent
[!] Couldn't open Firefox! Check the installation instructions again!
```
What is the problem? I tryed already some suggestio  on intern but with no good result :(

**Comment by D4Vinci** [comment]
The reason for this is you installed QRLJacker or firefox as root and firefox won't start as root, See #37
