### ISSUE TITLE
I have tried everything ''terminaltables''

### ISSUE THREAD

**Issue by rqqo** [OWASP/QRLJacking#79]
I tried all
Traceback (most recent call last):
  File "./QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/Escritorio/MITMf/QRLJacking/QRLJacker/core/Cli.py", line 5, in <module>
    from core import utils,db,module,Settings,browser
  File "/root/Escritorio/MITMf/QRLJacking/QRLJacker/core/utils.py", line 5, in <module>
    from terminaltables import AsciiTable as table
ImportError: cannot import name 'AsciiTable' from 'terminaltables' (unknown location)

HELP ME PLS!

**Comment by sheikhzadasuhail** [comment]
same .....anyone here to help

**Comment by D4Vinci** [comment]
If you installed the framework as in the README.MD file, you would have installed all the requirements like terminaltables!
