### ISSUE TITLE
Error after opening Firefox

### ISSUE THREAD

**Issue by ANKANPAL007** [OWASP/QRLJacking#84]
Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by blackcrush** [comment]
you fixed this error?????

**Comment by RUGMJ7443** [comment]
+1
