### ISSUE TITLE
python error 

### ISSUE THREAD

**Issue by jigsaw678** [OWASP/QRLJacking#97]
python3 QrlJacker.py
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 5, in <module>
    from core import utils,db,module,Settings,browser
  File "/root/QRLJacking/QRLJacker/core/utils.py", line 5, in <module>
    from terminaltables import AsciiTable as table
ModuleNotFoundError: No module named 'terminaltables'

**Comment by melbadry9** [comment]
- Run the following commands and the issue should be fixed.
```
pip3 install -r requirements.txt
```
